export const ACTIVITIES = [
  /* ── SCHÉMA D'UNE ACTIVITÉ (modèle Vivido) ─────────────────────────────
     photo : "" = dégradé CSS | URL = vraie photo
  ───────────────────────────────────────────────────────────────────────── */

  { id: 1, slug: "kayak-paddle-lac-neuchatel",
    cat: "outdoor", type: "eau", levelKey: "easy", duration: "2-3 h",
    saison: ["printemps", "ete", "automne"], tone: "water",
    photo: "https://images.unsplash.com/photo-1440993443326-9e9f5aea703a?w=800&q=80",
    prix: "CHF 80",
    whatsapp: "Bonjour ! Je suis interesse(e) par l'activite Kayak & paddle sur le lac. Pouvez-vous me donner plus d'infos ?",
    fr: { title: "Kayak & paddle sur le lac", location: "Neuchatel - rives du lac",
      desc: "Pagayez sur les eaux turquoise du plus grand lac entierement suisse, vue sur les Alpes les jours clairs." } },

  { id: 2, slug: "randonnee-creux-du-van",
    cat: "outdoor", type: "rando", levelKey: "hard", duration: "4-5 h",
    saison: ["printemps", "ete", "automne"], tone: "forest",
    photo: "https://images.unsplash.com/photo-1501555088652-021faa106b9b?w=800&q=80",
    prix: "Sur demande",
    whatsapp: "Bonjour ! Je suis interesse(e) par la randonnee au Creux du Van. Pouvez-vous m'indiquer les tarifs ?",
    fr: { title: "Randonnee au Creux du Van", location: "Noiraigue - Val-de-Travers",
      desc: "Le grand amphitheatre rocheux du Jura : 160 m de falaises, bouquetins et panorama sur les trois lacs." } },

  { id: 3, slug: "gorges-de-lareuse",
    cat: "outdoor", type: "rando", levelKey: "medium", duration: "3 h",
    saison: ["printemps", "ete", "automne"], tone: "forest",
    photo: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
    prix: "Sur demande",
    whatsapp: "Bonjour ! Je souhaite en savoir plus sur la balade dans les Gorges de l'Areuse.",
    fr: { title: "Gorges de l'Areuse", location: "Boudry -> Noiraigue",
      desc: "Un sentier le long de la riviere emeraude, entre ponts de pierre, cascades et fraicheur de la foret." } },

  { id: 4, slug: "ski-raquettes-bugnenets",
    cat: "outdoor", type: "neige", levelKey: "medium", duration: "Journee",
    saison: ["hiver"], tone: "snow",
    photo: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&q=80",
    prix: "Sur demande",
    whatsapp: "Bonjour ! Je suis interesse(e) par une journee ski & raquettes aux Bugnenets.",
    fr: { title: "Ski & raquettes aux Bugnenets", location: "Les Bugnenets-Savagnieres",
      desc: "Pistes familiales et itineraires raquettes sur les hauteurs du Jura neuchatelois." } },

  { id: 5, slug: "balade-degustation-vignes",
    cat: "outdoor", type: "gastro", levelKey: "easy", duration: "2 h",
    saison: ["ete", "automne"], tone: "vine",
    photo: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800&q=80",
    prix: "Sur demande",
    whatsapp: "Bonjour ! La balade & degustation dans les vignes m'interesse. Quels sont les tarifs ?",
    fr: { title: "Balade & degustation dans les vignes", location: "Littoral neuchatelois",
      desc: "Marchez entre les rangs de vigne du Littoral et degustez un Neuchatel blanc chez le vigneron." } },

  { id: 6, slug: "latenium-musee-archeologie",
    cat: "indoor", type: "culture", levelKey: "easy", duration: "2 h",
    saison: ["printemps", "ete", "automne", "hiver"], tone: "stone",
    photo: "https://images.unsplash.com/photo-1767507006111-e802239ef4f3?w=800&q=80",
    prix: "Sur demande",
    whatsapp: "Bonjour ! Je souhaite visiter le Latenium. Pouvez-vous m'indiquer les tarifs et horaires ?",
    fr: { title: "Latenium, parc & musee d'archeologie", location: "Hauterive",
      desc: "Le plus grand musee archeologique de Suisse, au bord du lac : 50 000 ans d'histoire a ciel ouvert." } },

  { id: 7, slug: "spa-bains-lac",
    cat: "indoor", type: "bien", levelKey: "easy", duration: "1/2 journee",
    saison: ["printemps", "ete", "automne", "hiver"], tone: "water",
    photo: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80",
    prix: "Sur demande",
    whatsapp: "Bonjour ! Je suis interesse(e) par une session spa & bains face au lac.",
    fr: { title: "Spa & bains face au lac", location: "Neuchatel",
      desc: "Bassins chauds, sauna et soins pour decompresser apres l'effort, le regard pose sur l'eau." } },

  { id: 8, slug: "atelier-cuisine-terroir",
    cat: "indoor", type: "gastro", levelKey: "easy", duration: "3 h",
    saison: ["printemps", "ete", "automne", "hiver"], tone: "stone",
    photo: "https://images.unsplash.com/photo-1507048331197-7d4ac70811cf?w=800&q=80",
    prix: "Sur demande",
    whatsapp: "Bonjour ! L'atelier cuisine du terroir m'interesse. Quels sont les tarifs ?",
    fr: { title: "Atelier cuisine du terroir", location: "Neuchatel - table d'hote",
      desc: "Mettez la main a la pate autour des produits locaux, puis passez a table avec le chef." } },

  { id: 9, slug: "maison-de-labsinthe",
    cat: "indoor", type: "culture", levelKey: "easy", duration: "1-2 h",
    saison: ["printemps", "ete", "automne", "hiver"], tone: "vine",
    photo: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=800&q=80",
    prix: "Sur demande",
    whatsapp: "Bonjour ! Je souhaite visiter la Maison de l'Absinthe a Motiers.",
    fr: { title: "Maison de l'Absinthe", location: "Motiers - Val-de-Travers",
      desc: "L'histoire de la Fee verte la ou elle est nee - degustation comprise." } },
];